### ISSUE TITLE
Ctrl-v for docu

### ISSUE THREAD

**Issue by pepper179** [redmica/redmica#104]
I tried to use Redmica 1.2 and 2.0.
Both versions do not working Ctrl-v to insert pictures into Documents.
It works for News, Tickets, Wiki. However it is not working for Documents.
What's wrong anything??

Both version have been deployed on ubuntu 20.04.
I referred to the following site:(in Japanese site)
https://blog.redmine.jp/articles/mica-1_2/install/ubuntu/
https://qiita.com/0to9/items/f03a8ee6cbc64146ac57

**Comment by ishikawa999** [comment]
@pepper179 
Could you use RedMica 2.1?
The problem of not being able to paste images in documents was fixed 3 months ago and has been released in RedMica 2.1.
https://redmine.org/issues/36686

**Comment by pepper179** [comment]
Really? I will do that. Thank you!

**Comment by ishikawa999** [comment]
Close as it seems to have been resolved. Thanks for using it!
