### ISSUE TITLE
Update redmine_theme_farend_bleuclair

### ISSUE THREAD

**Issue by ishikawa999** [redmica/redmica#13]
RedMica's bleuclair is an older version and has some problems.
Example:  
* https://github.com/farend/redmine_theme_farend_bleuclair/commit/3e6407c9688f713b9cb295219ec872645fb4875a
* https://github.com/farend/redmine_theme_farend_bleuclair/commit/845c2da4acc91966b677f0aa0d2cdf016e5410ef

Please update version of bleuclair.

**Comment by vividtone** [comment]
Merged GH-14. The fix is going to be delivered in v1.0.1.
